trigger: none

variables:
- group: pipeline_vargroup

jobs:
  - job: Kernel_5
    pool:
      name: $(agentPoolName)
      demands:
      - Agent.Name -equals $(hostname1)
    workspace:
      clean: all
    steps:
      - script: |
          cd ebpf_telemetry          
          rm -rf ./build
          mkdir ./build && cd build
          cmake ..
          make all
        displayName: CMake Build All
  - job: Kernel_4_12
    pool:
      name: $(agentPoolName)
      demands:
      - Agent.Name -equals $(hostname2)
    workspace:
      clean: all
    steps:
      - script: |
          cd ebpf_telemetry          
          rm -rf ./build
          mkdir ./build && cd build
          cmake ..
          make all
        displayName: CMake Build All